#!/bin/bash
docker build --build-arg openjdk_version=openjdk-8-jre -f ./Dockerfile -t eskabetxe/openjdk:jre8 .
docker build --build-arg openjdk_version=openjdk-8-jdk -f ./Dockerfile -t eskabetxe/openjdk:jdk8 .