#!/bin/bash
docker build --build-arg openjdk_version=openjdk-8-jre -f $DOCKERFILE_PATH -t eskabetxe/openjdk:jre8 .
docker build --build-arg openjdk_version=openjdk-8-jdk -f $DOCKERFILE_PATH -t eskabetxe/openjdk:jdk8 .